name: todo_movies
description: A Flutter Project made for a job test at mobile2you.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management and dependency injection
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.3
  equatable: ^2.0.3

  # HTTP Client
  dio: ^4.0.6

  # Other packages
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
