name: todo_movies
description: A Flutter Project made for a job test at mobile2you.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management and dependency injection
  flutter_bloc: ^8.1.1
  provider: ^6.0.3
  equatable: ^2.0.5

  # HTTP Client
  dio: ^4.0.6
  either_dart: ^0.2.0

  # Other packages
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  palette_generator: ^0.3.3+1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Package for testing Dio requests
  http_mock_adapter: ^0.3.3

  # CLI to setup launcher icon and android package name
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  ios: true
  android: true
  image_path: "assets/launch/launch_icon.png"
